### ISSUE TITLE
Client-side public key verification

### ISSUE THREAD

**Issue by paragonie-scott** [Minds/mobile#19]
Let's assume an attacker (TAO at NSA, for example) compromises the server that the Minds client communicates with. What can be done to prevent them from replacing the public key that other clients receive with one of their own?

Typical case:

```
Alice -> Server: give me Bob's public key
Server -> Alice: here you go ----- BEGIN RSA PUBLIC KEY --- ...
```

Approaches that work (but some might not be the best UX):
- https://github.com/WhisperSystems/TextSecure/wiki/Using-TextSecure#verifying-keys
- https://security.stackexchange.com/questions/40915/how-is-otr-messaging-with-socialist-millionaire-protocol-smp-protected-from-ma
- https://otr.cypherpunks.ca/help/4.0.1/authenticate.php?lang=en

I would encourage you to carefully study what TextSecure does. https://github.com/WhisperSystems/TextSecure/wiki/ProtocolV2

**Comment by TMCMike** [comment]
Thanks for bringing this up! :D
