### ISSUE TITLE
Current working directory is not a Cordova-based project.

### ISSUE THREAD

**Issue by byteslick** [Minds/mobile#21]
This is my system information:

```
$ npm -v && ionic -v && cordova -v
4.0.5
2.1.18

6.4.0
```

When I try to do `cordova build ios` or `cordova build` I get this:

```
$ cordova build ios
Error: Current working directory is not a Cordova-based project.
```

```
$ cordova build
Error: Current working directory is not a Cordova-based project.
```

**Comment by byteslick** [comment]
**Update:**

Looks like its not a ionic/cordova project anymore. You have to install nativescript run it via

`tns run ios --emulator`

More details at:
https://docs.nativescript.org/tutorial/chapter-1

I suggest the moderators to update the ReadMe files

**Comment by markharding** [comment]
We're currently developing a few prototypes of a new app. For the current
app check out the v1.1 branch. https://github.com/Minds/mobile/tree/v1.1
