### ISSUE TITLE
React Native Minds

### ISSUE THREAD

**Issue by dancomanlive** [Minds/mobile#36]
Minds mobile powered by React Native. Sounds good? Join https://www.minds.com/groups/profile/823949610664599552 now!

**Comment by markharding** [comment]
We're releasing next week. Stay tuned.

**Comment by dancomanlive** [comment]
@markharding Awesome! Is there a dev channel/group?(aside from the one I just created)

**Comment by Serkan-devel** [comment]
@dancomanlive Probably this one https://www.minds.com/groups/profile/365903183068794880
